#!/bin/bash
# Full drop-in nginx for Gnoland TM2 RPC + gRPC + static valopers JSON.
# Run as root from anywhere (e.g. ~/endpoint/testnet or /opt/explorer/scripts).
#
# SAFETY (P1):
#   Default = config-only (NO stop nginx, NO certbot). Safe to re-run.
#   ISSUE_CERTS=1  → stop nginx + certbot standalone + write conf (first install / renew).
#   Example first install:  ISSUE_CERTS=1 bash endpoint-gnoland.sh
#   Example re-apply conf:  bash endpoint-gnoland.sh
#
# PATHS (production-portable — no hard dependency on user "hermes"):
#   VALOPERS_JSON       absolute path to cron output JSON (highest priority)
#   GNO_EXPLORER_ROOT   explorer tree (else $APP_HOME/explorer)
#   Default             $APP_HOME/explorer/public/data/gno-valopers.json
#   APP_HOME            SUDO_USER home if run via sudo, else $HOME
#                       → `sudo bash endpoint-gnoland.sh` does NOT resolve to /root/explorer
#   Cron must write the SAME file nginx aliases (see cron-gno-valopers.sh).
#
# === KONFIGURASI ===
BASE_DOMAIN="${BASE_DOMAIN:-shazoes.xyz}"
RPC_SUB="${RPC_SUB:-gnoland-testnet-rpc}"
GRPC_SUB="${GRPC_SUB:-gnoland-testnet-grpc}"
RPC_PORT="${RPC_PORT:-42657}"
GRPC_PORT="${GRPC_PORT:-42090}"
CONF_FILE="${CONF_FILE:-/etc/nginx/sites-enabled/gnoland-testnet}"

# Real deploy user home (sudo-safe)
if [ -n "${SUDO_USER:-}" ] && [ "$SUDO_USER" != "root" ]; then
  APP_HOME="$(getent passwd "$SUDO_USER" | cut -d: -f6)"
else
  APP_HOME="${HOME}"
fi
APP_HOME="${APP_HOME:-/root}"

EXPLORER_ROOT="${GNO_EXPLORER_ROOT:-$APP_HOME/explorer}"
# Opsi A default: data plane di luar explorer ($HOME/gno-valopers).
# Legacy: VALOPERS_JSON=$EXPLORER_ROOT/public/data/gno-valopers.json
VALOPERS_JSON="${VALOPERS_JSON:-$APP_HOME/gno-valopers/data/gno-valopers.json}"

ISSUE_CERTS="${ISSUE_CERTS:-0}"

if [ "$ISSUE_CERTS" = "1" ]; then
  # === HENTIKAN NGINX SEMENTARA (hanya untuk Certbot standalone) ===
  echo "⏳  ISSUE_CERTS=1 → menghentikan Nginx sementara untuk Certbot standalone..."
  sudo systemctl stop nginx

  echo "🔐 Membuat sertifikat SSL untuk $RPC_SUB.$BASE_DOMAIN"
  sudo certbot certonly --standalone -d "$RPC_SUB.$BASE_DOMAIN" --register-unsafely-without-email --agree-tos

  echo "🔐 Membuat sertifikat SSL untuk $GRPC_SUB.$BASE_DOMAIN"
  sudo certbot certonly --standalone -d "$GRPC_SUB.$BASE_DOMAIN" --register-unsafely-without-email --agree-tos
else
  echo "ℹ️  ISSUE_CERTS=0 (default) → skip certbot, nginx tetap jalan. Set ISSUE_CERTS=1 hanya untuk first install/renew."
  if [ ! -f "/etc/letsencrypt/live/$RPC_SUB.$BASE_DOMAIN/fullchain.pem" ]; then
    echo "⚠️  Sertifikat RPC belum ada. Jalankan sekali: ISSUE_CERTS=1 $0"
  fi
fi

# Pastikan file registry kebaca nginx (kalau belum ada, location tetap — 404 sampai cron).
# Layout default: $APP_HOME/explorer/public/data (sama ide dengan $HOME/explorer/...).
if [ -f "$VALOPERS_JSON" ]; then
  chmod a+r "$VALOPERS_JSON" 2>/dev/null || true
fi
chmod a+x "$APP_HOME" \
  "$APP_HOME/explorer" \
  "$APP_HOME/explorer/public" \
  "$APP_HOME/explorer/public/data" 2>/dev/null || true
# If JSON lives outside ~/explorer (VALOPERS_JSON override), still fix traverse
if [ -f "$VALOPERS_JSON" ] || [ -d "$(dirname "$VALOPERS_JSON")" ]; then
  _path="$VALOPERS_JSON"
  while [ -n "$_path" ] && [ "$_path" != "/" ]; do
    _path="$(dirname "$_path")"
    [ -d "$_path" ] || continue
    chmod a+x "$_path" 2>/dev/null || true
    case "$_path" in
      "$APP_HOME"|"$APP_HOME"/*|/home|/home/*|/opt|/opt/*|/var|/var/*|/srv|/srv/*) ;;
      *) break ;;
    esac
  done
fi
sudo mkdir -p "$(dirname "$VALOPERS_JSON")" 2>/dev/null || mkdir -p "$(dirname "$VALOPERS_JSON")" 2>/dev/null || true

echo "📁 APP_HOME=$APP_HOME"
echo "📁 VALOPERS_JSON=$VALOPERS_JSON"
echo "📁 EXPLORER_ROOT=$EXPLORER_ROOT"

# === BUAT KONFIGURASI NGINX ===
echo "📄 Menulis konfigurasi Nginx → $CONF_FILE"
sudo tee "$CONF_FILE" > /dev/null <<EOF
# RPC — Tendermint2 + static valoper registry (explorer SPA)
# Generated by endpoint-gnoland.sh — VALOPERS_JSON=$VALOPERS_JSON
server {
    listen 443 ssl http2;
    server_name $RPC_SUB.$BASE_DOMAIN;

    ssl_certificate     /etc/letsencrypt/live/$RPC_SUB.$BASE_DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$RPC_SUB.$BASE_DOMAIN/privkey.pem;

    # Live valopers JSON (cron → file). HARUS sebelum location / agar tidak ke TM2.
    # URL: https://$RPC_SUB.$BASE_DOMAIN/static/gno-valopers.json
    location = /static/gno-valopers.json {
        alias $VALOPERS_JSON;
        default_type application/json;
        add_header Access-Control-Allow-Origin * always;
        add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Accept, Content-Type" always;
        add_header Cache-Control "public, max-age=60" always;
        if (\$request_method = OPTIONS) {
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods "GET, OPTIONS";
            add_header Access-Control-Allow-Headers "Accept, Content-Type";
            add_header Content-Length 0;
            return 204;
        }
    }

    location / {
        proxy_pass http://127.0.0.1:$RPC_PORT/;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_http_version 1.1;
        proxy_set_header Connection "upgrade";
    }
}

# gRPC
server {
    listen 443 ssl http2;
    server_name $GRPC_SUB.$BASE_DOMAIN;

    ssl_certificate     /etc/letsencrypt/live/$GRPC_SUB.$BASE_DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$GRPC_SUB.$BASE_DOMAIN/privkey.pem;

    location / {
        grpc_pass grpc://127.0.0.1:$GRPC_PORT;
        grpc_set_header Host \$host;
        grpc_set_header X-Real-IP \$remote_addr;
        grpc_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    }
}

# REDIRECT HTTP → HTTPS
server {
    listen 80;
    server_name $RPC_SUB.$BASE_DOMAIN $GRPC_SUB.$BASE_DOMAIN;

    location / {
        return 301 https://\$host\$request_uri;
    }
}
EOF

# === AKTIFKAN DAN MUAT ULANG NGINX ===
echo "🚀 Menguji dan menyalakan ulang Nginx..."
if sudo systemctl is-active --quiet nginx; then
  sudo nginx -t && sudo systemctl reload nginx
else
  sudo nginx -t && sudo systemctl start nginx
fi

echo "✅  Siap diakses melalui:"
echo "   RPC      → https://$RPC_SUB.$BASE_DOMAIN"
echo "   gRPC     → https://$GRPC_SUB.$BASE_DOMAIN"
echo "   Valopers → https://$RPC_SUB.$BASE_DOMAIN/static/gno-valopers.json"
echo "   (file)   → $VALOPERS_JSON"
echo ""
echo "Cek cepat:"
echo "  curl -sI https://$RPC_SUB.$BASE_DOMAIN/static/gno-valopers.json | head"
echo "  curl -s  https://$RPC_SUB.$BASE_DOMAIN/status | head -c 120"
echo ""
echo "Catatan: re-run aman (default ISSUE_CERTS=0). First cert: ISSUE_CERTS=1 $0"
echo "Default path: \$HOME/explorer/public/data/gno-valopers.json (sudo → SUDO_USER home, not /root)"
echo "Override: VALOPERS_JSON=/var/lib/gnoland/gno-valopers.json GNO_EXPLORER_ROOT=/opt/explorer $0"
