#!/bin/bash
# install-nginx-gnoland.sh — Gnoland RPC + static gno-valopers + gno-gov (Opsi A, RPC-ONLY)
#
# Fresh-from-zero: cert di-issue otomatis kalau belum ada, reuse kalau sudah.
# Satu perintah, langsung jadi:
#   sudo -E bash install-nginx-gnoland.sh
#
# RPC-only by design: gRPC publik dihapus (sumber spam scanner .php ke error.log).
#
# Opsi A data plane (default):
#   VALOPERS_JSON=$APP_HOME/gno-valopers/data/gno-valopers.json  (di-update cron */10)
#   GOV_JSON=$APP_HOME/gno-valopers/data/gno-gov.json            (di-update cron */30)
set -euo pipefail

# === KONFIGURASI ===
BASE_DOMAIN="${BASE_DOMAIN:-shazoes.xyz}"
RPC_SUB="${RPC_SUB:-gnoland-testnet-rpc}"
RPC_PORT="${RPC_PORT:-42657}"
CONF_FILE="${CONF_FILE:-/etc/nginx/sites-enabled/gnoland-testnet}"
WEBROOT_ACME="${WEBROOT_ACME:-/var/www/html}"

# Real deploy user home (sudo → bukan /root)
if [ -n "${SUDO_USER:-}" ] && [ "$SUDO_USER" != "root" ]; then
  APP_HOME="$(getent passwd "$SUDO_USER" | cut -d: -f6)"
else
  APP_HOME="${HOME}"
fi
APP_HOME="${APP_HOME:-/root}"

# Opsi A default (di luar explorer, file fresh dari cron). Override: VALOPERS_JSON=... / GOV_JSON=...
VALOPERS_JSON="${VALOPERS_JSON:-$APP_HOME/gno-valopers/data/gno-valopers.json}"
GOV_JSON="${GOV_JSON:-$APP_HOME/gno-valopers/data/gno-gov.json}"

FQDN_RPC="${RPC_SUB}.${BASE_DOMAIN}"
CERT_RPC="/etc/letsencrypt/live/${FQDN_RPC}"

if [ "$(id -u)" -ne 0 ]; then
  echo "ERROR: jalankan dengan sudo -E"
  echo "  sudo -E bash $0"
  exit 1
fi

echo "==> APP_HOME=$APP_HOME"
echo "==> VALOPERS_JSON=$VALOPERS_JSON"
echo "==> GOV_JSON=$GOV_JSON"
echo "==> CONF_FILE=$CONF_FILE"

command -v nginx >/dev/null
command -v certbot >/dev/null || { echo "ERROR: certbot belum terpasang"; exit 1; }

# DNS soft-check (jangan print IP publik)
if getent ahostsv4 "$FQDN_RPC" >/dev/null 2>&1; then
  echo "    DNS $FQDN_RPC OK"
else
  echo "WARN: DNS $FQDN_RPC belum resolve — cert bisa gagal, pastikan A/AAAA record ada"
fi

mkdir -p "$(dirname "$VALOPERS_JSON")" "$WEBROOT_ACME"
# pastikan file valopers + gov + parent kebaca nginx (traverse sampe APP_HOME)
if [ -f "$VALOPERS_JSON" ]; then
  chmod a+r "$VALOPERS_JSON" 2>/dev/null || true
fi
if [ -f "$GOV_JSON" ]; then
  chmod a+r "$GOV_JSON" 2>/dev/null || true
fi
_path="$VALOPERS_JSON"
while [ -n "$_path" ] && [ "$_path" != "/" ]; do
  _path="$(dirname "$_path")"
  [ -d "$_path" ] && chmod a+x "$_path" 2>/dev/null || true
  case "$_path" in
    "$APP_HOME"|"$APP_HOME"/*|/home|/home/*|/opt|/opt/*|/var|/var/*|/srv|/srv/*) ;;
    *) break ;;
  esac
done

# === CERT: issue otomatis kalau belum ada, reuse kalau sudah ===
ensure_rpc_cert() {
  if [ -f "${CERT_RPC}/fullchain.pem" ] && [ -f "${CERT_RPC}/privkey.pem" ]; then
    echo "==> [cert] reuse $FQDN_RPC"
    return 0
  fi
  echo "==> [cert] belum ada → issue fresh $FQDN_RPC"
  # HTTP bootstrap vhost untuk ACME (nginx tetap hidup → webroot)
  tee "$CONF_FILE" >/dev/null <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name ${FQDN_RPC};
    location ^~ /.well-known/acme-challenge/ {
        root ${WEBROOT_ACME};
        default_type "text/plain";
        allow all;
    }
    location / { return 404; }
}
EOF
  nginx -t && (systemctl reload nginx 2>/dev/null || systemctl start nginx)
  if certbot certonly --webroot -w "$WEBROOT_ACME" -d "$FQDN_RPC" \
      --register-unsafely-without-email --agree-tos --non-interactive 2>/dev/null; then
    echo "    webroot OK $FQDN_RPC"
  else
    echo "    FALLBACK standalone (stop nginx sebentar) $FQDN_RPC"
    systemctl stop nginx || true
    certbot certonly --standalone -d "$FQDN_RPC" \
      --register-unsafely-without-email --agree-tos --non-interactive
    systemctl start nginx || true
  fi
  if [ ! -f "${CERT_RPC}/fullchain.pem" ]; then
    echo "ERROR: cert gagal di-issue untuk $FQDN_RPC (cek DNS + port 80)"
    exit 1
  fi
}
ensure_rpc_cert

SSL_OPTIONS=""
SSL_DH=""
[ -f /etc/letsencrypt/options-ssl-nginx.conf ] && SSL_OPTIONS="    include /etc/letsencrypt/options-ssl-nginx.conf;"
[ -f /etc/letsencrypt/ssl-dhparams.pem ] && SSL_DH="    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;"

echo "==> writing RPC vhost → $CONF_FILE"
tee "$CONF_FILE" >/dev/null <<EOF
# Gnoland TM2 RPC + static valopers + gov (Opsi A, RPC-only)
# Generated by install-nginx-gnoland.sh — VALOPERS_JSON=${VALOPERS_JSON} GOV_JSON=${GOV_JSON}
# Re-run safe (cert auto-reuse)

# REDIRECT HTTP → HTTPS (+ ACME)
server {
    listen 80;
    listen [::]:80;
    server_name ${FQDN_RPC};

    location ^~ /.well-known/acme-challenge/ {
        root ${WEBROOT_ACME};
        default_type "text/plain";
        allow all;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

# RPC — Tendermint2 + static valoper registry (explorer SPA)
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${FQDN_RPC};

    ssl_certificate     ${CERT_RPC}/fullchain.pem;
    ssl_certificate_key ${CERT_RPC}/privkey.pem;
${SSL_OPTIONS}
${SSL_DH}

    # HARUS sebelum location / — jangan proxy ke TM2
    # URL: https://${FQDN_RPC}/static/gno-valopers.json
    location = /static/gno-valopers.json {
        alias ${VALOPERS_JSON};
        default_type application/json;
        add_header Access-Control-Allow-Origin * always;
        add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Accept, Content-Type" always;
        add_header Cache-Control "public, max-age=60" always;
        if (\$request_method = OPTIONS) {
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods "GET, OPTIONS";
            add_header Access-Control-Allow-Headers "Accept, Content-Type";
            add_header Content-Length 0;
            return 204;
        }
    }

    # URL: https://${FQDN_RPC}/static/gno-gov.json
    location = /static/gno-gov.json {
        alias ${GOV_JSON};
        default_type application/json;
        add_header Access-Control-Allow-Origin * always;
        add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Accept, Content-Type" always;
        add_header Cache-Control "public, max-age=60" always;
        if (\$request_method = OPTIONS) {
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods "GET, OPTIONS";
            add_header Access-Control-Allow-Headers "Accept, Content-Type";
            add_header Content-Length 0;
            return 204;
        }
    }

    location / {
        proxy_pass http://127.0.0.1:${RPC_PORT}/;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_http_version 1.1;
        proxy_set_header Connection "upgrade";
    }
}
EOF

nginx -t
if systemctl is-active --quiet nginx; then
  systemctl reload nginx
else
  systemctl start nginx
fi

echo ""
echo "✅ Gnoland nginx ready (RPC-only)"
echo "   RPC      → https://${FQDN_RPC}"
echo "   Valopers → https://${FQDN_RPC}/static/gno-valopers.json"
echo "   Gov      → https://${FQDN_RPC}/static/gno-gov.json"
echo "   (files)  → ${VALOPERS_JSON}"
echo "              ${GOV_JSON}"
echo ""
echo "Cron Opsi A (user crontab, BUKAN systemd nginx):"
echo "  */10 * * * * GNO_VALOPERS_ROOT=\$HOME/gno-valopers GNO_EXPLORER_ROOT=\$HOME/explorer GNO_VALOPERS_AUTO_COMMIT=0 \$HOME/gno-valopers/scripts/cron-gno-valopers.sh"
echo "  */30 * * * * GNO_VALOPERS_ROOT=\$HOME/gno-valopers GNO_EXPLORER_ROOT=\$HOME/explorer \$HOME/gno-valopers/scripts/cron-gno-gov.sh"
echo ""
echo "Cek:"
echo "  curl -sI https://${FQDN_RPC}/static/gno-valopers.json | head"
echo "  curl -sI https://${FQDN_RPC}/static/gno-gov.json | head"
echo "  curl -s  https://${FQDN_RPC}/status | head -c 120"
